name: arknightstools
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase Core Flutter SDK
  firebase_core: ^0.4.4+3

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  firebase_performance: ^0.3.1+8
  firebase_ml_vision: ^0.9.3+8
  firebase_admob: ^0.9.3+2

  # Reading and writing simple key-value pairs
  shared_preferences: ^0.5.7+2

  # A collection of animated loading indicators for flutter
  flutter_spinkit: ^4.1.2+1

  # Implement a beautiful and dynamic Material Design Speed Dial, with labels, animated icons and hide on scrolling
  flutter_speed_dial: ^1.2.5

  # API for managing permissions
  permission_handler: ^5.0.0+hotfix.6

  # A plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^0.6.6+4

  # Provides an API for querying information about an application package
  package_info: ^0.4.0+17

  # Display inline video with other Flutter widgets on Android and iOS
  video_player: ^0.10.11+1

  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.12.1
  dio: ^3.0.9
  dio_http_cache: ^0.2.6

  # Parse text and extract parts using predefined types like url, phone and email and also supports Regex
  flutter_parsed_text: ^1.2.4

  # A plugin for launching a URL in the mobile platform. Supports iOS and Android.
  url_launcher: ^5.5.0

  # Flutter package for Eva Icons. Eva Icons is a pack of more than 480 beautifully crafted Open Source icons for common actions and items.
  eva_icons_flutter: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appicon.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/icons/appicon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/avatars/
    - assets/example/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
